hw13_01: Igor Chvyrov
tamkovich/tms-python-autumn pull request #113
Opened 2020-12-09 12:42 UTC by Red4m

2021-01-02 15:22 UTC, tamkovich requested changes

2021-01-02 15:22 UTC, tamkovich commented on src/pack/exceptions.py
> +def valid():
Функция отвечает за действие. И получает аргумент как число -- > добавь docstring и переименуй

И так с каждой функцией

В остальном апрув)

2021-01-07 19:45 UTC, tamkovich requested changes

2021-01-07 19:45 UTC, tamkovich commented on src/pack/ui_func.py
> +        a = valid_argument(a)
```suggestion
        a = get_valid_int_argument()
```

Пускай функция get_valid_int_argument ничего не принимает и всю логику чтения с консоли делает внтутри

2021-01-07 19:45 UTC, tamkovich commented on src/pack/exceptions.py
> +def valid_sign(a: str) -> str:
same as above

2021-01-07 21:02 UTC, Red4m commented on src/pack/ui_func.py
> +        a = valid_argument(a)
Так у меня же так и было))

2021-01-12 10:03 UTC, tamkovich approved these changes
LGTM, thanks for your work!

2023-08-10 18:47 UTC, closed without merging