HW5: Igor Chvyrov
tamkovich/tms-python-autumn pull request #55
Opened 2020-11-15 11:39 UTC by Red4m

2020-11-29 16:12 UTC, tamkovich requested changes
https://github.com/tamkovich/tms-python-autumn/blob/hw_reviews/src/Common.md

5

2020-11-29 16:12 UTC, tamkovich commented on src/task_5_1.py
> +            continue
в конце цикла continue не нужен

2020-11-29 16:12 UTC, tamkovich commented on src/task_5_1.py
> +    X = input("input X: ")
добавь проверку типа на X

2020-11-29 16:12 UTC, tamkovich commented on src/task_5_1.py
> +            Z = int(X) + int(Y)
перевод в int чисел X и Y лучше сделать до цикла, так как эта операция может повторяться несколько раз

2020-11-29 16:12 UTC, tamkovich commented on src/task_5_10.py
> +            "time_of_departure": datetime.time(int(input(f'hour departure {i+1} : ')),
5

2020-11-29 16:12 UTC, tamkovich commented on src/task_5_2.py
> +    elif not number.isdigit() or number.startswith("-"):
"-10".isdigit()

 Строка выше вернет уже False, потому здесь стоит оставить только проверку на startswith

2020-11-29 16:12 UTC, tamkovich commented on src/task_5_3.py
> +for i in range(1, len_numbers):
Лучше здесь создать переменную _range = range(1, len_numbers), которую потом здесь и ниже использовать

2020-12-01 20:31 UTC, Red4m commented on src/task_5_10.py
> +            "time_of_departure": datetime.time(int(input(f'hour departure {i+1} : ')),
????

2021-01-02 12:33 UTC, tamkovich approved these changes
LGTM, thanks for your work!

2023-08-10 18:47 UTC, closed without merging